const SUCCESSFUL_REQUEST = 200;
const BAD_REQUEST = 400 ;
const NO_CONTENT = 204 ;
const CREATEED_REQUEST = 201 ;
const NOT_FOUND = 404 ;
const INTERNAL_SERVER_ERROR = 500 ;

module.exports = {
  SUCCESSFUL_REQUEST,
  BAD_REQUEST,
  NO_CONTENT,
  CREATEED_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR
};