const SUCCESSFUL_REQUEST = 200;
const BAD_REQUEST = 400 ;
const NO_CONTENT = 204 ;
const CREATED_REQUEST = 201 ;
const NOT_FOUND = 404 ;
const INTERNAL_SERVER_ERROR = 500
const UNAUTHORIZED = 401 ;
const CONFLICT = 409 ;
const FORBIDDEN = 403 ;

module.exports = {
  SUCCESSFUL_REQUEST,
  BAD_REQUEST,
  NO_CONTENT,
  CREATED_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  UNAUTHORIZED,
  CONFLICT,
  FORBIDDEN
};